{
    'name': 'final',
    'version': '18.0.0.0.0',
    'category': 'Custom',
    'summary': 'Пустой модуль для дальнейшей разработки.',
    'description': "",
    'author': 'final',
    'website': '',
    'depends': ['base', 'hr', 'calendar', 'mail'],
    'data': [
        'security/final_security.xml',
        'security/ir.model.access.csv',
        'data/training_type_data.xml',
        'data/final_cron.xml',
        'views/final_training_type_views.xml',
        'views/final_order_views.xml',
        'views/hr_employee_views.xml',
        'views/final_trainer_views.xml',
        'views/create_trainer_wizard_views.xml',
        'views/attach_trainer_wizard_views.xml',
        'views/apply_trainer_wizard_views.xml',
        'views/trainer_cabinet_views.xml',
        'views/final_center_training_price_views.xml',
        'views/final_training_booking_views.xml',
        'views/training_booking_wizard_views.xml',
        'views/training_booking_reject_wizard_views.xml',
        'views/training_booking_cancel_wizard_views.xml',
        'views/training_booking_reschedule_wizard_views.xml',
        'views/training_booking_reject_cancel_wizard_views.xml',
        'views/training_booking_reject_reschedule_wizard_views.xml',
        'views/final_balance_transaction_views.xml',
        'views/res_partner_views.xml',
        'views/balance_deposit_wizard_views.xml',
        'views/final_training_recurring_views.xml',
        'views/statistics_report_wizard_views.xml',
        'views/profit_report_wizard_views.xml',
        'reports/profit_report_views.xml',
        'views/final_menu.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
